name: Publish Package
on:
  push:
    tags: ["*"]
    paths:
      - 'package.json'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write    
    steps:
      - uses: actions/checkout@v4

      # PUBLICANDO EM NPM
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Publish to NPM
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}


      # PUBLICANDO EM GITHUB PACKAGE
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@heliomarpm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Publish to GitHub Packages
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

